// <auto-generated />
using System;
using CatMicroservice.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CatMicroservice.Migrations
{
    [DbContext(typeof(CatContext))]
    [Migration("20200502154500_intiial")]
    partial class intiial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CatMicroservice.Models.Cat", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CatCharacter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CatLitter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CatMedicalCondition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CatName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CatVetAddress1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CatVetAddress2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CatVetCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CatVetName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CatVetPhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CatVetPostCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ChekedIn")
                        .HasColumnType("bit");

                    b.Property<bool?>("ChekedOut")
                        .HasColumnType("bit");

                    b.Property<Guid>("Customer")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfLastVac")
                        .HasColumnType("datetime2");

                    b.Property<int>("MealType")
                        .HasColumnType("int");

                    b.Property<string>("TagID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Vaccination")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("Cats");
                });
#pragma warning restore 612, 618
        }
    }
}
